config_tags = [
    ("随机热点SSID", "randomwifissid"),
    ("随机热点密码", "randomwifipwd"),
    ("禁用日志", "lowerlog"),
    ("开启自动热点", "openwifi"),
    ("关闭自动热点(优先)", "closewifi"),
    ("开启自动备份系统", "SystemBackup"),
    ("每日更换iKun图标", "ikunicon"),
    ("禁用主程序", "ZhangProtectLock"),
    ("关闭全局权限设置", "AutoPreCFlag"),
    ("关闭杀毒白名单设置", "excludeflag"),
    ("关闭进程优先级调度", "Disable_sys_dispatch"),
    ("关闭自动电源计划机制", "donotautopower"),
    ("锁定省电节能模式", "powerkeep"),
    ("使用休眠代替关机", "usehibernate"),
    ("禁用强制蓝屏快捷键", "donotforcebluescreen"),
    ("隐藏电源选项关机", "hide_shutdown"),
    ("隐藏电源选项重启", "hide_restart"),
    ("隐藏电源选项睡眠", "hide_sleep"),
    ("隐藏电源选项休眠", "hide_hibernate"),
    ("禁用时钟信息栏", "do_no_show_clock_info"),
    ("使用360来开启AP", "use_360_ap_flag"),
]
config_tags.sort(key=lambda x: len(x[0]))
